### ISSUE TITLE
AMSI raise error

### ISSUE THREAD

**Issue by gitglo** [adrecon/ADRecon#21]
Hello,
thanks for your effort in this project.
On recent windows systems ADRecon.ps1 raise the error “**This script contains malicious content and has been blocked by your antivirus software**”, this should be related to the AMSI component.
Do you know which section of the code is detected as malicious and how to fix/bypass it?

**Comment by prashant3535** [comment]
Unfortunately AMSI is a cat n mouse game ... will need to check what it is flagging now. In the mean time payloads from sites like amsi.fail or similar should help bypass it.

**Comment by gitglo** [comment]
Again many thanks  for your effort and ready response.
